### PR TITLE
Update contributions and add relevant information

### PR DESCRIPTION
**Pull request by Matteas-Eden**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

The contributions listed currently on `master` are out-of-date and do not reflect the latest contributions from contributors. 
Also, there exists some confusion about what the types of contributions are and how to achieve different types of contributions.

## What is the new behavior?

The contributions will be updated to more accurately reflect contributions of various contributors. Also, there is now a file describing the contributions, how to add contributions what they each represent and how to achieve each of the contributions.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [x] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

In addition to the changes described above, the branch was updated with the latest changes from master.

Internal Issue (If applicable):

### CODE REVIEW

**Comment by Pyxxil** [comment]
I think the idea for this is nice in theory, I'm just a little skeptical of it in practice.

My main concern would be perception by outsiders (in our case the lecturers) with regards to contributions to the project. I, personally, am not too sure about the current state (for example I think we'd all be classified maintainers, but again that may be my understanding of the tag, and I'd consider myself having done docs (meeting minutes template, license, privacy policy)), and am actually worried that this could potentially lead to grade considerations further down the track (especially because it has the potential to be used as 'evidence' that someone did less contribution than they claim).

While I also appreciate that this would be mostly for what we've each added to the repository, I feel it outshines slightly the contributions external to the repository that any of us contribute.

**Comment by Matteas-Eden** [comment]
@Pyxxil I hear your concerns. While I do share them in part, I also feel that when it comes to evaluating contributions from the perspective of the University, they will only be concerned with the peer reviews. I don't think they'll change people's grades based on emojis in the README.

In regards to the contribution tags, I'm all ears to what `Maintainer` should represent. I was using it to sort of represent administrative contributions I made as the owner of the repository, but if you feel there's a different interpretation that is more inclusive I'm more than willing to use it.

**Comment by Pyxxil** [comment]
I was basing the idea of maintainer off of that of the idea of a software maintainer: A person, or group of people, who organise the repository, make changes to the code in the form of patches/commits, etc.

I am curious what you mean by administrative contributions though, so I'd like to hear what you mean by that.

**Comment by Matteas-Eden** [comment]
I see what you mean, but I feel like that definition has a large overlap with `Code` contributions, which describe changes to the code through patches/commits, etc.

With 'administrative changes', I was referring to such things as: defining issue/PR templates, creating a Kanban board, setting up GitHub pages (separate to actually hosting the game itself, simply the default display of the README) and creating the repository itself.

Hopefully that clears up my meaning.

**Comment by Pyxxil** [comment]
Okay, that's understandable. In which case, I'd suggest the following:

I feel I should get maintainer status because the Kanban board was a discussion between the two of us, and I appreciate you actually putting it together but it makes me feel like I'm the lesser because I didn't put do so. I also defined the meeting minutes template, which should be in the same category as the issue/PR templates you talked about.

Speaking of the meeting minutes, I would think those would be considered an administrative change/task simply because they are just that -- admin. In which case, I think @KimberleyEvans-Parker should get maintainer status for her part in doing those.

I'd also like to raise the point about the Kanban board again: All of us have been manually moving tasks to the In Progress portion of the board. I'd consider that an administrative task/change similar to you setting it up originally.

So, again, I would think everyone should have the maintainer status. Would you agree?

**Comment by Matteas-Eden** [comment]
You raise valid points. I would argue that the meeting minutes @KimberleyEvans-Parker authored comes under Documentation, which is the contribution I added for her with the most recent commit.

I appreciate the point about the Kanban and the templates for the meeting minutes, so I will add the Maintainer contribution for you. At this point, I don't see a point in simply giving it to everyone. After updating your contribution, everyone will have an equal amount of contributions listed, which I would think is satisfactory.

**Comment by Pyxxil** [comment]
Thanks for that. However, in my opinion, the meeting minutes fall more under administrative tasks than they do documentation -- they aren't exactly supposed to be used to understand the project, more as a collection of discussions we've had that we can use as a log.

As for the kanban stuff, I think having us down for that, but not @Frosty273 and @KimberleyEvans-Parker, seems a little unfair seeing as they've effectively done the same amount of work surrounding it as we have. The manual moving of tasks is undoubtedly an administrative task/change. I'd also say that, despite how little of a contribution it may be perceived as, it's still just that: a contribution. And I personally believe that everyone should be recognised for every contribution they make, no matter how small.

**Comment by Matteas-Eden** [comment]
I believe that the meeting minute _templates_ fall under administration, but that the _write-up_ of each week's minutes is documentation.

Apologies for being unclear in regards to Kanban - I'm not considering it an administrative task. It is an expectation that any contributor to the project would be using it, so I do not believe the mere use of it justifies recognition as an additional contribution. It's simply not substantial enough to qualify as a contribution in my view.

If we are unable to resolve this discussion, perhaps we should bring it up with the rest of the team.

**Comment by Matteas-Eden** [comment]
As per the team discussion, I concede my side of the argument.

**Review by Pyxxil — APPROVED** [review]
LGTM

**Pull request merged**
