### PR TITLE
Enhance the Journal for Readability

### LINKED ISSUE #165: Improve formatting of journal
**User Story**
As a player, I'd like the journal to be more readable and present information such that it is concise but also highlights important details.

**Acceptance Criteria**
- Journal entries follow a consistent format that is concise
- Journal is formatted so as to separate logs from different events
- Colour coding is added to journal to identify player, monsters, items, spells and key values

**Notes**

The format examples given aren't strict - the assignee is free to create other formats as they see fit.

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
The journal fills up quickly, and it's difficult to keep track of what happened when. All the text seemingly blurs together.

**Describe the solution you'd like**
There needs to be a degree of separation between logs from different actions. The logs themselves should follow a set format, appropriate to what is being logged. Different aspects of the message should be coloured to draw attention to and highlight important details.

**Format Examples*

`<entity> attacked <entity> with <attack_value> against <defence_value>`
`<entity> hits!`
`<entity> misses!`
`<entity> casts <spell>`
`<entity> attacks <entity> with <spell>`

### PR DESCRIPTION
**Pull request by Pyxxil**
GitHub Issue (If applicable): #165 

## PR Type

What kind of change does this PR introduce?
- Feature
- Refactoring (no functional changes, no api changes)

## What is the current behavior?
The journal, while it does log most of the stuff it should, does so in a less than ideal way (i.e. it is difficult to read, and is bland colour-wise).

## What is the new behavior?
The journal now contains all sorts of colours, is much easier to read (with line spacing, entry spacing).

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

Internal Issue (If applicable): closes #165

### CODE REVIEW

**Comment by Pyxxil** [comment]
I want to write this here before I forget. Items to add to the journal:
 - Items sold?
 - Gold/Exp gain
 - Defeated <entity>?
 - Regain Mana (with passive and potion being separate items)

I'll add to this list as I think of more things (although, it may be that we need to merge the other PR's first, update this branch, make the changes, and then merge this branch)

**Comment by Pyxxil** [comment]
With the above, I think it makes some sense to merge #181, #175, #169, and perhaps #179 before this one.

**Review by Matteas-Eden — CHANGES_REQUESTED** [review]
It's good (really good), there are just a few minor things I'd like to address:
* Having a log of passively restoring mana clogs up the journal logs, and could probably be removed
* When levelling up, the health and mana values don't the respective green/blue colouring
* For defeating an enemy, it says `YOU VANQUISH THE !`
    * Shouldn't it be `VANQUISHED` to be consistent with the tense of the rest of the journal?
    * The enemy name isn't displayed

**Review by Matteas-Eden — APPROVED** [review]
LGTM.

**Pull request merged**
