### PR TITLE
Dice based combat

### LINKED ISSUE #136: Modify combat interactions to involve STR and DEX
**User Story**
As a game designer, I'd like a player's strength and dexterity to determine whether attacks hit monsters.

**Acceptance Criteria**

- Monsters are assigned an `attack_value` and `defence_value`
- Player's attack damage is determine solely by weapon
- A player's `attack_value` is determined by a virtual d20 roll summed with their STR modifier
- A player's `defence_value` is determined by the total defence value of their items summed with their DEX modifier
- `attack_value` and `defence_value` are used in determining the success of attacks in combat
- There is some visual feedback to the player indicating the success of an attack

**Notes**

It may be necessary to adjust the attack and defence values of weapon and armour items, as well as monsters.

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Currently, the Strength and Dexterity ability scores are not useful and are not associated with any gameplay elements.

**Describe the solution you'd like**
Each monster will have an `attack_value` and a `defence_value`. Combat interactions between the player and monsters will be changed to follow these sequences:

*Player declares attack on Monster*
- A virtual d20 is rolled and the player's strength ability modifier is added to that roll, creating an `attack_value`
- This `attack_value` is compared to the monster's `defence_value` (`attack_value >= defence_value`)
- If that comparison evaluates to `true`, then damage is dealt to the monster. Otherwise, no damage is dealt

*Monster declares attack on Player*
- The `defence_value` of the player is determined by summing up the total defence gained from equipped items and the player's dexterity ability modifier
- The `attack_value` of the attacking monster is compared to the `defence_value` of the player (`attack_value >= defence_value`)
- If that comparison evaluates to `true`, then damage is dealt to the player. Otherwise, no damage is dealt

### LINKED ISSUE #138: Modify weapons to use virtual dice rolls to determine damage
**User Story**
As a game designer, I'd like the in-game weapons to make use of virtual dice rolls to determine their damage values instead of using hardcoded attack values so that the game more closely follows the design seen in *Dungeons and Dragons*.

**Acceptance Criteria**

- Weapons use a combination of virtual dice rolls to determine damage

**Notes**

Standard dice notation should be adhered to: https://en.wikipedia.org/wiki/Dice_notation

---

**Why is this feature needed? Please describe the problem your requested feature wants to solve**
Weapons currently use hardcoded attack values to represent their damage, which does not line up with the new design inspired by DnD.

**Describe the solution you'd like**
Each weapon will have a combination of dice (and appropriate constants) associated with it that is then used to determine damage dealt on each hit. 

**Use Case**
A weapon held by the player deals damage listed as `2d4 + 2`. A player attacks a monster. The damage dealt would then be calculated as follows:
`Math.floor(Math.random() * 4 + 1) + Math.floor(Math.random() * 4 + 1) + 2`

A visual demonstration may be seen [here](https://matteas.nz/dice-roller/?notation=2d4+2&roll)

### PR DESCRIPTION
**Pull request by Pyxxil**
GitHub Issue (If applicable): #136 

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
Attacks are done based simply on the damage a player can deal (determined by their weapons damage), and similarly for monsters.

## What is the new behavior?
Attacks have a preliminary stage where first a d20 is rolled, the player's strength modifier is added, and if the accumulated value is greater than the defense of the monster then they succeed in their attack -- and then the damage given by their weapon is calculated and applied to the monster.

If the monster's attack value is greater than that of the defensive value of the player, they too will succeed the attack check and they will hit the player for their attack value.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [x] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information
 - A discussion around how the monsters should actually attack is required.

Internal Issue (If applicable): closes #136

### CODE REVIEW

**Review by Matteas-Eden — CHANGES_REQUESTED** [review]
The original issue was a little vague, so I'll put clarifications here.

**Monsters**
There are three values required specifically for combat are attack, defence and damage. Attack and defence are both used to determine the success of attacks (i.e. did I hit/did I get hit). Damage is separate to this. For each monster, there should be a hardcoded attack and defence value (like there is right now, except they'll need to modified slightly to make sense in the new system). Similarly to the weapons in #139, monsters should have damage represented by dice notation.

**Armour**
Each piece of armour should contribute to a player's defence, but this should be balanced in such a way that a player's defence doesn't go above 20 (or at least not easily).

**Comment by Pyxxil** [comment]
> The original issue was a little vague, so I'll put clarifications here.
> 
> **Monsters**
> There are three values required specifically for combat are attack, defence and damage. Attack and defence are both used to determine the success of attacks (i.e. did I hit/did I get hit). Damage is separate to this. For each monster, there should be a hardcoded attack and defence value (like there is right now, except they'll need to modified slightly to make sense in the new system). Similarly to the weapons in #139, monsters should have damage represented by dice notation.
> 
> **Armour**
> Each piece of armour should contribute to a player's defence, but this should be balanced in such a way that a player's defence doesn't go above 20 (or at least not easily).

If that's the case, the only thing I can see that this isn't doing is having the damage done by the monsters to be similar to how the player's damage is calculated. So, what was your issue with it at the moment that isn't related to balancing or having the monsters damage be based on dice rolls?

**Comment by Matteas-Eden** [comment]
> 
> 
> > The original issue was a little vague, so I'll put clarifications here.
> > **Monsters**
> > There are three values required specifically for combat are attack, defence and damage. Attack and defence are both used to determine the success of attacks (i.e. did I hit/did I get hit). Damage is separate to this. For each monster, there should be a hardcoded attack and defence value (like there is right now, except they'll need to modified slightly to make sense in the new system). Similarly to the weapons in #139, monsters should have damage represented by dice notation.
> > **Armour**
> > Each piece of armour should contribute to a player's defence, but this should be balanced in such a way that a player's defence doesn't go above 20 (or at least not easily).
> 
> If that's the case, the only thing I can see that this isn't doing is having the damage done by the monsters to be similar to how the player's damage is calculated. So, what was your issue with it at the moment that isn't related to balancing or having the monsters damage be based on dice rolls?

I didn't have many issues with it - your implementation is quite good. The only other thing I might suggest is additional visual feedback. At the moment, if a player's attack fails, it's not clear why it failed. Perhaps that could be solved in part by #140, but I feel it may be necessary to add some sort of pop-up. Perhaps utilise the snackbar to say an attack missed? I'm open to suggestions.

**Comment by Pyxxil** [comment]
I figured that would all be handled in #140, however at the moment they will know they miss if they don't see the attack animation (I don't think it's full proof, but if we plan on doing #140 anyways, we may as well ignore that for now).

But if I have to add the dice based rolls for Monsters anyways, so I can technically add the snack bar notification for the moment if preferred.

**Comment by Matteas-Eden** [comment]
> 
> 
> I figured that would all be handled in #140, however at the moment they will know they miss if they don't see the attack animation (I don't think it's full proof, but if we plan on doing #140 anyways, we may as well ignore that for now).
> 
> But if I have to add the dice based rolls for Monsters anyways, so I can technically add the snack bar notification for the moment if preferred.

For the moment I'd prefer to have the snackbar notification. That way the player knows that their attack _actually_ missed, and it wasn't merely a case of the animation not showing (i.e. a runtime error).

**Comment by Pyxxil** [comment]
I've already done it, you'll get a video soon.

**Review by Matteas-Eden — CHANGES_REQUESTED** [review]
When the player doesn't have a weapon equipped and tries to attack, the game crashes (`TypeError: weapon is undefined`). Due to how attacking was changed this is more or less expected. I can think of two solutions:
- Don't allow the player to attack if they don't have a weapon
- Allow the player to attack unarmed and define its damage

**Review by Matteas-Eden — DISMISSED** [review]
Thanks for the change for unarmed combat. Given that the damage for no weapon and *Rusty Sword* are now the same, I think it would make sense to increase the damage of the latter, but it's not a blocking change.

**Review by Matteas-Eden — APPROVED** [review]
LGTM

**Pull request merged**
