### PR TITLE
Update docs with notes about adapting DnD

### PR DESCRIPTION
**Pull request by Matteas-Eden**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

- Documentation content changes

## What is the current behavior?

There is some documentation in the `docs` folder, but that documentation present does not fully address the adaption of *Dungeons and Dragons* to *Roll for Reaction*. In particular, the current documentation lacks detail surrounding some of the more basic aspects of *Dungeons and Dragons* and how these aspects will be implemented in *Roll for Reaction*.

## What is the new behavior?

A markdown file which addresses the above concerns has been added. The class 'Warlock' was also changed to 'Wizard' in the existing documentation.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [x] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [ ] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Review by KimberleyEvans-Parker — CHANGES_REQUESTED** [review]
I have a couple of concerns about this pull request.  The biggest was that it is not linked to an issue - I was under the impression that all pull requests should be linked to an issue (due to what we've discussed in the past, good practice and being useful to the team.

**Comment by KimberleyEvans-Parker** [comment]
It would be nice if the pull request was more descriptive; 'notes' is very vague as to what this pull request changes and not entailing as to what it does change.

**Comment by Matteas-Eden** [comment]
> 
> 
> I have a couple of concerns about this pull request. The biggest was that it is not linked to an issue - I was under the impression that all pull requests should be linked to an issue (due to what we've discussed in the past, good practice and being useful to the team.

I decided not to link it to an issue, because I felt that I would be making an issue for the pull request as opposed to making a pull request that addresses an issue. That is to say, the issue would have been created arbitrarily.

**Comment by Matteas-Eden** [comment]
Upon further consideration, I've concluded that these changes aren't required. The information contained in the documentation files this pull request attempts to integrate with `master` will be integrated into the wiki instead.

**Pull request closed without merging**
